# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('vanetmobility', ['mobility'])
    module.source = [
        'model/RouteElement.cc',
        'model/SumoMobility.cc',
        'model/vanetmobility.cc',
        'tinyxml/tinystr.cc',
        'tinyxml/tinyxml.cc',
        'tinyxml/tinyxmlerror.cc',
        'tinyxml/tinyxmlparser.cc',        
        'helper/vanetmobility-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('vanetmobility')
    module_test.source = [
        'test/vanetmobility-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'vanetmobility'
    headers.source = [
        'model/RouteElement.h',
        'model/SumoMobility.h',
        'model/vanetmobility.h',
        'tinyxml/tinystr.h',
        'tinyxml/tinyxml.h',    
        'helper/vanetmobility-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

